FROM ubuntu:22.04
ARG TARGETPLATFORM
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY ${TARGETPLATFORM}/gridw /app/gridw
WORKDIR /app
ENTRYPOINT ["/app/gridw"]
