version: "3"

tasks:
  install-deps:
    cmds:
    - go mod tidy

  default:
    desc: "Build grid"
    deps: [install-deps]
    cmds:
    - go build -o bin/api ./cmd/api/main.go
    - go build -o bin/controller ./cmd/controller/main.go
    - go build -o bin/worker ./cmd/worker/main.go
    - go build -o bin/grid ./cmd/client/main.go
    sources:
    - "**/**/*.go"
    generates:
    - bin/api
    - bin/controller
    - bin/worker
    - bin/grid

  test:
    deps:
    - install-deps
    desc: "Run tests"
    cmds:
    - go test -v ./... -cover

  clean:
    desc: "Clean up"
    cmds:
    - rm -f bin/*
