version: "3"

tasks:
  install-deps:
    cmds:
    - go mod tidy

  default:
    desc: "Build grid"
    deps: [install-deps]
    cmds:
    - go build -o bin/grid ./cmd/controller/main.go
    - go build -o bin/gridw ./cmd/worker/main.go
    - go build -o bin/gridc ./cmd/client/main.go
    sources:
    - "**/**/*.go"
    generates:
    - bin/grid
    - bin/gridw
    - bin/gridc

  test:
    desc: "Run all tests"
    cmds:
    - go test ./... -v -race -count=1

  scenario:
    desc: "Run a scenario job against a local compose cluster"
    cmds:
    - ./scenarios/run.sh {{.CLI_ARGS}}

  scenario:up:
    desc: "Start the scenario cluster (stays running)"
    cmds:
    - docker compose -f scenarios/compose.yaml up -d --build --wait

  scenario:down:
    desc: "Tear down the scenario cluster"
    cmds:
    - docker compose -f scenarios/compose.yaml down --timeout 5

  scenario:logs:
    desc: "Tail scenario cluster logs"
    cmds:
    - docker compose -f scenarios/compose.yaml logs -f

  clean:
    desc: "Clean up"
    cmds:
    - rm -f bin/*

  release:snapshot:
    desc: "Build a local release snapshot (no publish)"
    cmds:
      - goreleaser release --snapshot --clean
